### ISSUE TITLE
Collateral handling for DCAP

### ISSUE THREAD

**Issue by Niederb** [integritee-network/pallets#104]
- Extract a version of `sgx_ql_qve_collateral_t`
- Define the struct `sgx_ql_qve_collateral_t` in the teerex pallet
- Provide de-/encoding for the struct
- The goal is that we can send the collateral data along with the report
  - This is just for now. Later we (probably) want to store the collateral on the chain

**Comment by Niederb** [comment]
Some relevant code sections from the DCAP repository:
- `sgx_qve_verify_quote(...)` is the main function for the verification logic
- `QuoteVerifier` contains the bulk of the actual verification and calls into the classes described below
- `EnvlaveReportVerifier` is used to verify the report vom the quoting enclave against the information from the collateral
- `EnclaveIdentityVerifier` is used to verify the quoting enclave collateral information
- In `ParserUtils.cpp` are OID values that are needed to get values out of the PCK certificate
- `TCBInfoVerifier` is used to verify the tcb info collateral information

**Comment by clangenb** [comment]
Collateral handling is implemented in https://github.com/integritee-network/pallets/blob/master/teerex/sgx-verify/src/collateral.rs
