### ISSUE TITLE
Refactorings regarding dcap

### ISSUE THREAD

**Issue by Niederb** [integritee-network/pallets#119]
After we introduced it makes sense to do some additional refactorings in order to make the API clearer. Separated this into its own issue to not further complicate things regarding merging.
Todo:
- Rename `register_enclave` to `register_ias_enclave`
- Use the `Fmspc` type definition from `teerex-primitives` also in `remote_attestation.rs` in the worker as it is duplicated there

**Comment by brenzi** [comment]
also change the extrinsic name in the worker as this is a breaking change
