### ISSUE TITLE
Extract the GPL3 stuff from this repository

### ISSUE THREAD

**Issue by clangenb** [integritee-network/pallets#144]
So it seems that if we licence on crate in the repository under the GPL-3 licence, we are supposed to licence everything under GPL3 if it is in the same repository. See the following answer I got:

> If you create a Rust crate and license it under the GPL-3 license, then you would need to license the entire repository that contains the crate under the GPL-3 license as well. The GPL-3 license is a copyleft license, which means that any derivative works, including the entire repository that contains the Rust crate, must be released under the same license.

> This means that anyone who wants to use the code in your repository, including the Rust crate, would need to comply with the terms of the GPL-3 license, including releasing any derivative works under the GPL-3 license.

>It's important to keep in mind that the GPL-3 license has a number of specific requirements, such as providing copies of the source code and displaying a copy of the license. It's good practice to include a copy of the GPL-3 license in the repository, as well as to indicate in the repository's README file or in other documentation that the repository is licensed under the GPL-3 license.

> It's also worth noting that GPL-3 is not the only open-source license available and you can choose a different license that better fits your needs or project if you want to.

Hence, we might want to extract the DCAP GPL3 licenced stuff into a separate repository so that we don't need to licence the entire repository under GPL3.

**Comment by brenzi** [comment]
dcap/teerex is now licensed as MS-RSL, not GPLv3, so I guess we need take no further action
