### ISSUE TITLE
Mistmatching WeightInfo for pallet_teerex

### ISSUE THREAD

**Issue by Kailai-Wang** [integritee-network/pallets#156]
I assume the `weights.rs` for pallet_teerex (and maybe other pallets) hasn't been updated for a long time, we tried to run a [runtime benchmarking](https://github.com/litentry/litentry-parachain/actions/runs/4428581826/jobs/7767886420) for these pallets and discovered a few problems:

- `<T as Config>::WeightInfo::publish_hash()` expects two parameters but none is provided in the trait
- `register_dcap_enclave` and `register_quoting_enclave` are missing in the benchmarks

This is our generated [runtime weights file](https://github.com/litentry/litentry-parachain/blob/53b77f23af35156172574a281a4b52380c9b6f01/runtime/rococo/src/weights/pallet_teerex.rs) for pallet-teerex using upstream `benchmarking.rs`

**Comment by clangenb** [comment]
The one with the DCAP attestations is know, we have for now put in conservative values just to ensure that no-one can attack the chain. We have an open issue for that: https://github.com/integritee-network/pallets/issues/125

I did create a benchmark and have also run it in the tests for the `publish_hash`  (I thought that I also run it in the node, but maybe I forgot). Thanks for the notice!
