### ISSUE TITLE
a-posteriori reviews in globo

### ISSUE THREAD

**Issue by brenzi** [integritee-network/pallets#206]
Many incremental changes in pallets will need another review once everything is completed and tested with node and worker

PR's to revisit:
* #204
* #205
* node integration: https://github.com/integritee-network/integritee-node/pull/180

**Comment by brenzi** [comment]
@clangenb you may have indirectly reviewed this already by now. But for the sake of completeness I wanted to raise your awareness to the things I fast-track merged.

**Comment by clangenb** [comment]
Done
