### ISSUE TITLE
use crates.io as source for substrate git deps

### ISSUE THREAD

**Issue by clangenb** [integritee-network/pallets#229]
I don't really see a reason not to do this except for lack of resources. :)

**Comment by clangenb** [comment]
Also consider that we might want to introduce the subxt dependency and the xcm test again at this point, see #230.

**Comment by brenzi** [comment]
can you clarify plz? I don't understand what this issue is about

**Comment by clangenb** [comment]
Sorry, was a hasty PR description, and it is even wrong. I wanted to say switch to crates.io as source for substrate deps.

**Comment by brenzi** [comment]
done
