### ISSUE TITLE
stable-fee pallet requirements

### ISSUE THREAD

**Issue by echevrier** [integritee-network/pallets#34]
To ensure that costs are stable and predictable for Integritee users, the Integritee service is priced in USD. Payment, however, occurs in an equivalent amount of TEER tokens, based on the live exchange rate with USD.

# Stakeholder
* A Dapp operator deploying on integritee who likes predictable and stable (in fiat currency) operation expenses.
* Any intermediary service that accepts fiat payments and pays the on-chain TEER fees on behalf of their customer

# Story
* The Integritee network adjusts its usage fees according to the current exchange rate of TEER/USD as delivered by oracles with the goal of stable USD equivalent operation costs for projects deploying on Integritee 

# Requirements
* The fee for a transaction should be stable in USD over time, independently of the token value. Some short term variations are acceptable. 
* The usage fee target will be denominated in USD
* The extrinsic fee payment will be made in TEER 
* The ratio between USD and TEER  will be the average of several USD/TEER exchange rates from different sources. 
* The Governance can set a minimal and a maximal conversion value to avoid extreme cases. 
* The USD/TEER exchange rate must be tracked live.
* The different exchange rates will be provided by trusted exchange rate oracles (teeracles).

# Solution
Implement a Stable Fees pallet
...

**Comment by echevrier** [comment]
# Stakeholder:
*

# User Story

# Requirements

# Solution

**Comment by brenzi** [comment]
approved
