### ISSUE TITLE
Remove outdated `TODO` comment

### ISSUE THREAD

**Issue by haerdib** [integritee-network/pallets#56]
I believe the `TODO` comment
https://github.com/integritee-network/pallets/blob/4d1b0e9d412b4e3b94f3e5afd853213b6ecc97b7/teerex/src/lib.rs#L175-L177

is outdated now?
We already have https://github.com/integritee-network/pallets/blob/4d1b0e9d412b4e3b94f3e5afd853213b6ecc97b7/teerex/src/lib.rs#L418-L422 implemented.

**Comment by clangenb** [comment]
Yes, this can be removed.
