### ISSUE TITLE
remove dependency on the api-client

### ISSUE THREAD

**Issue by clangenb** [integritee-network/pallets#72]
The refactoring of the primtives has brought the dependency of the api-client here. In my opinion, this brings unnecessary dependency complexity into the pallets and should be avoided because it also makes the upgrade process more tedious, which was at least for the pallets fairly easy until now as they were decoupled from our other repositories.

**Comment by mullefel** [comment]
So it might make sense to move some crates back to the worker repository? With the change in how we want to approach finality in the parentchain, we don't need these crates in the pallets repo anymore. So it probably makes sense to move them back again, to avoid confusion and minimize dependencies of the pallets repo?

**Comment by clangenb** [comment]
I agree, this makes sense.
