### ISSUE TITLE
Implement sidechain finality - simplified version

### ISSUE THREAD

**Issue by mullefel** [integritee-network/pallets#76]
As part of #855, we need to change our current implementation of the sidechain finality in the sidechain pallet.

* Instead of storing a list of finalized sidechain headers, we only store the latest finalized sidechain block (identified by block number and hash)
* In this simplified first version, we don't employ a majority algorithm to determine if a block is considered finalized. Instead, just finalize everything we receive from the first validateer. First being the validateer registered first at pallet Teerex.

- [x] create a new pallet call new `confirm_imported_sidechain_block` as a copy from 'confirm_proposed_sidechain_block'
- [x] make all tests use the new call
- [x] refactor 'confirm_imported_sidechain_block' to use a simple storage value, with blocknumber and hash.
- [x] change 'confirm_imported_sidechain_block', so that it receives blocknumber and hash (not the full SidechainHeader) and adjust the tests accordingly (if needed).

- [x] implement [#922](https://github.com/integritee-network/worker/issues/922) (i. e. use the new pallet-call, don't use the old one anymore).

- [x] remove pallet call 'confirm_proposed_sidechain_block'
- [x] Remove dependency on `sidechain-primitives` crate (since we don't need `SidechainHeader` anymore, we only store hash and number) https://github.com/integritee-network/worker/issues/924
- [x] Increase transaction_version in referencing integritee-node (see comment below).

**Comment by masapr** [comment]
@mullefel Can you check, if you're ok with my changes? ... sorry for being picky with the wording here, but this task is not a refactoring, we change the logic (because we only process calls from the "first" validateer).

**Comment by mullefel** [comment]
Of course, yes! You're right, it's not a refactoring but a change in the whole logic 👍

**Comment by masapr** [comment]
Input from @clangenb : 
 if we remove the old confirm sidechain block in the future. This requires a bump in the transaction version in the runtime. From the docs:

```
/// All existing dispatches are fully compatible when this number doesn't change. If this
/// number changes, then `spec_version` must change, also.
///
/// This number must change when an existing dispatchable (module ID, dispatch ID) is changed,
/// either through an alteration in its user-level semantics, a parameter
/// added/removed/changed, a dispatchable being removed, a module being removed, or a
/// dispatchable/module changing its index.
///
/// It need *not* change when a new module is added or when a dispatchable is added.
pub transaction_version: u32,
```
